trigger:
- master

pool:
  name: Windows VM

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(System.DefaultWorkingDirectory)/Portfolio.Web'

- script: |
    npm run build:prod
  displayName: 'npm run build:prod'

- script: |
    npm run lint
  displayName: 'Lint'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '6.4.0'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    projects: '$(System.DefaultWorkingDirectory)/**/*.sln'
    custom: 'msbuild'
    arguments: '-restore -p:configuration=$(BuildConfiguration);DeployOnBuild=true;UseWPP_CopyWebApplication=true;PipelineDependsOnBuild=false'''

- task: PublishBuildArtifacts@1
  displayName: 'Publish PurpleLogger'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/portfolio/Portfolio.Api/bin/$(BuildConfiguration)/net7.0'
    ArtifactName: 'Portfolio API'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Portfolio Frontend'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/portfolio/Portfolio.Web/dist'
    ArtifactName: 'Portfolio Web'
    publishLocation: 'Container'
